### ISSUE TITLE
create a mentor branch

### ISSUE THREAD

**Issue by rachaelcodes** [foundersandcoders/testing-tdd-intro#1]
It might be useful to have a mentor branch with some questions. Here are some I've used:

1) why do we test our code? (could ask a few people)
2) what is the TDD cycle? - get the group to draw up and explain the red-green-refactor cycle
3) why use TDD?
4) what sorts of functions are easier to test?
5) in tape, what's the difference between 'equal', 'deepEqual' and 'ok'? (i got them to google this)

**Comment by oliverjam** [comment]
Yeah these are all good things to get people talking/thinking about. Would a branch or just a `QUESTIONS.md` work better for this?

**Comment by rachaelcodes** [comment]
yup, questions.md sounds like a good idea

**Comment by MynahMarie** [comment]
If it's ok I'll assign myself to create the QUESTIONS.md file because I think it's a great idea  :relaxed: We struggled quite a lot with testing in our cohort and I think part of the issue is that we didn't fully understand the methodology or relevance of testing until much later on.

**Comment by MynahMarie** [comment]
Did a PR, I didn't write the answers to each question in the file I created, instead I gave some of the references I found by doing some research on the subject. 

If anyone has more ideas on how to do this please let me know! 😸
